# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17xMLrQtghyYz1mFwe2gEQHcTT_rCykc7
"""

import random
from flask import Flask, render_template
from flask_socketio import SocketIO, emit

app = Flask(__name__)
app.config['SECRET_KEY'] = 'kanzoku-kun-v3-ultimate'
socketio = SocketIO(app)

# --- 55種類のカードデータベース ---
CARD_DB = [
    {"id": "Newbie", "name": "新入社員", "cost": 1, "power": 1, "type": "MACHINE", "upkeep": 0, "desc": "【登場時】1枚引く。"},
    {"id": "Staff", "name": "担当社員", "cost": 3, "power": 4, "type": "MACHINE", "upkeep": 1, "desc": "新入社員から進化(1)。"},
    {"id": "Chief", "name": "主任技術者", "cost": 5, "power": 8, "type": "MACHINE", "upkeep": 0, "desc": "担当社員から進化(1)。維持費0。"},
    {"id": "Senior", "name": "教育係の先輩", "cost": 2, "power": 3, "type": "MACHINE", "upkeep": 1, "desc": "新入社員のパワー+3。"},
    {"id": "Ace", "name": "現場のエース", "cost": 4, "power": 12, "type": "MACHINE", "upkeep": 2, "desc": "高出力な現場員。"},
    {"id": "Leader", "name": "現場代理人", "cost": 6, "power": 15, "type": "MACHINE", "upkeep": 1, "desc": "パワーが高いが低維持費。"},
    {"id": "Expert", "name": "ベテラン職人", "cost": 5, "power": 10, "type": "MACHINE", "upkeep": 2, "desc": "安定した計測値。"},
    {"id": "Clerk", "name": "事務員", "cost": 2, "power": 1, "type": "MACHINE", "upkeep": 0, "desc": "毎ターンAP+1回復。"},
    {"id": "Intern", "name": "実習生", "cost": 0, "power": 0, "type": "MACHINE", "upkeep": 0, "desc": "コスト0の囮。"},
    {"id": "SafetyOfficer", "name": "安全管理員", "cost": 3, "power": 2, "type": "MACHINE", "upkeep": 1, "desc": "現場の守り神。"},
    {"id": "LevelBasic", "name": "普通のレベル", "cost": 1, "power": 2, "type": "MACHINE", "upkeep": 1, "desc": "基本機材。"},
    {"id": "LevelAuto", "name": "オートレベル", "cost": 3, "power": 6, "type": "MACHINE", "upkeep": 1, "desc": "普通レベルから進化(1)。"},
    {"id": "StaffBasic", "name": "アルミスタッフ", "cost": 1, "power": 2, "type": "MACHINE", "upkeep": 1, "desc": "基本スタッフ。"},
    {"id": "StaffRef", "name": "反射スタッフ", "cost": 3, "power": 7, "type": "MACHINE", "upkeep": 1, "desc": "アルミから進化(1)。"},
    {"id": "TS", "name": "光波TS", "cost": 4, "power": 10, "type": "MACHINE", "upkeep": 2, "desc": "主力機材。"},
    {"id": "GNSS", "name": "GNSS衛星", "cost": 6, "power": 18, "type": "MACHINE", "upkeep": 3, "desc": "晴天時パワー+5。"},
    {"id": "Drone", "name": "UAVドローン", "cost": 5, "power": 14, "type": "MACHINE", "upkeep": 2, "desc": "濃霧の影響を受けない。"},
    {"id": "Scanner", "name": "3Dスキャナ", "cost": 8, "power": 25, "type": "MACHINE", "upkeep": 3, "desc": "最高クラスの出力。"},
    {"id": "UsedTS", "name": "中古のTS", "cost": 2, "power": 12, "type": "MACHINE", "upkeep": 2, "desc": "安価だが維持費がかさむ。"},
    {"id": "Laser", "name": "レーザー墨出し", "cost": 2, "power": 5, "type": "MACHINE", "upkeep": 1, "desc": "室内で真価を発揮。"},
    {"id": "Compass", "name": "コンパス", "cost": 1, "power": 1, "type": "MACHINE", "upkeep": 0, "desc": "方位を計測。"},
    {"id": "Tripod", "name": "三脚", "cost": 1, "power": 1, "type": "MACHINE", "upkeep": 0, "desc": "機材の土台。"},
    {"id": "Caliper", "name": "ノギス", "cost": 1, "power": 2, "type": "MACHINE", "upkeep": 1, "desc": "精密計測。"},
    {"id": "Scale", "name": "スケール", "cost": 1, "power": 1, "type": "MACHINE", "upkeep": 0, "desc": "基本。"},
    {"id": "Chalk", "name": "チョーク", "cost": 1, "power": 1, "type": "MACHINE", "upkeep": 0, "desc": "マーキング用。"},
    {"id": "Excavator", "name": "バックホー", "cost": 7, "power": 20, "type": "MACHINE", "upkeep": 4, "desc": "圧倒的パワー。"},
    {"id": "Rental", "name": "レンタル重機", "cost": 3, "power": 15, "type": "MACHINE", "upkeep": 5, "desc": "維持費が非常に高い。"},
    {"id": "SmallTruck", "name": "軽トラ", "cost": 2, "power": 1, "type": "MACHINE", "upkeep": 0, "desc": "設置をスムーズにする。"},
    {"id": "Concrete", "name": "生コン車", "cost": 5, "power": 10, "type": "MACHINE", "upkeep": 3, "desc": "雨天時パワー-5。"},
    {"id": "Pump", "name": "排水ポンプ", "cost": 3, "power": 0, "type": "MACHINE", "upkeep": 1, "desc": "豪雨のマイナスを無効化。"},
    {"id": "GenSet", "name": "発電機", "cost": 3, "power": 3, "type": "MACHINE", "upkeep": 1, "desc": "他機材のパワー+2。"},
    {"id": "Radio", "name": "無線機", "cost": 2, "power": 2, "type": "MACHINE", "upkeep": 1, "desc": "ドローンを強化。"},
    {"id": "Lights", "name": "投光器", "cost": 3, "power": 4, "type": "MACHINE", "upkeep": 1, "desc": "後半でパワーアップ。"},
    {"id": "Helmet", "name": "ヘルメット", "cost": 1, "power": 0, "type": "MACHINE", "upkeep": 0, "desc": "社員コストを軽減。"},
    {"id": "Barrier", "name": "工事看板", "cost": 2, "power": 0, "type": "MACHINE", "upkeep": 1, "desc": "相手の行動を抑制。"},
    {"id": "Elite", "name": "少数精鋭", "cost": 2, "power": 0, "type": "SPELL", "desc": "最大AP-1。社員2枚引く。"},
    {"id": "Decision", "name": "苦渋の決断", "cost": 0, "power": 0, "type": "SPELL", "desc": "手札から強カードを捨て最大AP+2。"},
    {"id": "Fund", "name": "資金調達", "cost": 4, "power": 0, "type": "SPELL", "desc": "永久に最大AP+1。"},
    {"id": "Transceiver", "name": "トランシーバー", "cost": 1, "power": 0, "type": "SPELL", "desc": "デッキから社員を1枚引く。"},
    {"id": "Safety", "name": "安全巡回", "cost": 3, "power": 0, "type": "SPELL", "desc": "相手の最大AP-1。"},
    {"id": "Lost", "name": "紛失事故", "cost": 3, "power": 0, "type": "SPELL", "desc": "相手のパワー10以上を1台破壊。"},
    {"id": "Note", "name": "電子野帳", "cost": 1, "power": 0, "type": "SPELL", "desc": "カードを2枚引く。"},
    {"id": "Repair", "name": "緊急修理", "cost": 2, "power": 0, "type": "SPELL", "desc": "APを5回復する。"},
    {"id": "Check", "name": "Wチェック", "cost": 2, "power": 0, "type": "SPELL", "desc": "カードを3枚引く。"},
    {"id": "Bush", "name": "藪払い", "cost": 2, "power": 0, "type": "SPELL", "desc": "相手の低コスト機を破壊。"},
    {"id": "Rush", "name": "突貫工事", "cost": 0, "power": 0, "type": "SPELL", "desc": "このターンAP+4。終了時、場の1台自壊。"},
    {"id": "Consult", "name": "気象予報", "cost": 1, "power": 0, "type": "SPELL", "desc": "次ターンの天候を晴天にする。"},
    {"id": "Training", "name": "資格手当", "cost": 2, "power": 0, "type": "SPELL", "desc": "社員1人のパワー+5、維持費0化。"},
    {"id": "NightWork", "name": "徹夜作業", "cost": 0, "power": 0, "type": "SPELL", "desc": "AP全快。ただし手札を全て捨てる。"},
    {"id": "Complaint", "name": "近隣クレーム", "cost": 3, "power": 0, "type": "SPELL", "desc": "相手のAPを3削る。"},
    {"id": "Boundary", "name": "境界未確定", "cost": 2, "power": 0, "type": "SPELL", "desc": "相手の機材1つを2ターン停止。"},
    {"id": "Overtime", "name": "残業指示", "cost": 2, "power": 0, "type": "SPELL", "desc": "1枚引いてAP+2。"},
    {"id": "Audit", "name": "会計検査", "cost": 4, "power": 0, "type": "SPELL", "desc": "相手の最大APを2削る。"},
    {"id": "Goal30", "name": "工期内完遂", "cost": 4, "power": 0, "type": "GOAL", "desc": "スコア30以上で勝利。"},
    {"id": "GoalFinal", "name": "社長決裁", "cost": 10, "power": 0, "type": "GOAL", "desc": "スコア10以上で勝利。"},
]

EVOLUTION_MAP = {"Staff": "Newbie", "Chief": "Staff", "LevelAuto": "LevelBasic", "StaffRef": "StaffBasic"}

class GameInstance:
    def __init__(self):
        self.reset()

    def reset(self):
        self.players = {
            "p1": {"ap": 2, "max_ap": 2, "score": 0, "hand": [], "field": [], "deck": [], "ready": False},
            "p2": {"ap": 2, "max_ap": 2, "score": 0, "hand": [], "field": [], "deck": [], "ready": False}
        }
        self.turn = "p1"
        self.turn_count = 1
        self.weather = "晴天"
        self.winner = None
        self.log = ["観測君VS ULTIMATE Ver 3.0 開始！"]

game = GameInstance()

@app.route('/')
def index():
    return render_template('ultimate.html')

@socketio.on('submit_deck')
def handle_deck(data):
    pid = data['player_id']
    game.players[pid]["deck"] = [dict(next(c for c in CARD_DB if c['id'] == cid)) for cid in data['deck']]
    random.shuffle(game.players[pid]["deck"])
    game.players[pid]["ready"] = True
    if game.players["p1"]["ready"] and game.players["p2"]["ready"]:
        for p in ["p1", "p2"]:
            game.players[p]["hand"] = [game.players[p]["deck"].pop(0) for _ in range(5) if game.players[p]["deck"]]
    emit('update_ui', vars(game), broadcast=True)

@socketio.on('play_card')
def handle_play(data):
    pid, idx = data['player_id'], data['card_index']
    if pid != game.turn or game.winner: return
    p = game.players[pid]
    card = p["hand"][idx]

    if game.weather == "豪雨" and card["type"] == "SPELL":
        game.log.append("【豪雨】スペル使用不可！")
        emit('update_ui', vars(game), broadcast=True)
        return

    play_cost = card["cost"]
    evolve_target_idx = -1
    is_evolution = False

    if card["id"] in EVOLUTION_MAP:
        base_id = EVOLUTION_MAP[card["id"]]
        for i, f in enumerate(p["field"]):
            if f["id"] == base_id:
                play_cost, evolve_target_idx, is_evolution = 1, i, True
                break

    if p["ap"] >= play_cost:
        card = p["hand"].pop(idx)
        p["ap"] -= play_cost
        if is_evolution:
            p["field"].pop(evolve_target_idx)
            p["field"].append(card)
        else:
            if card["type"] == "MACHINE": p["field"].append(card)
            if card["id"] == "Newbie" and p["deck"]: p["hand"].append(p["deck"].pop(0))
            if card["id"] == "Elite":
                p["max_ap"] = max(1, p["max_ap"]-1)
                for _ in range(2):
                    if p["deck"]: p["hand"].append(p["deck"].pop(0))
            elif card["id"] == "Fund": p["max_ap"] += 1
            elif card["id"] == "Note":
                for _ in range(2):
                    if p["deck"]: p["hand"].append(p["deck"].pop(0))
            elif card["id"] == "Repair": p["ap"] = min(p["max_ap"], p["ap"] + 5)

        game.log.append(f"{pid.upper()}: {card['name']} 使用")
        if card["id"] == "GoalFinal" and p["score"] >= 10: game.winner = pid
        if card["id"] == "Goal30" and p["score"] >= 30: game.winner = pid
        recalc_scores()
    emit('update_ui', vars(game), broadcast=True)

def recalc_scores():
    for pid in ["p1", "p2"]:
        s = 0
        for c in game.players[pid]["field"]:
            v = c["power"]
            if c["id"] == "GNSS" and game.weather == "晴天": v += 5
            if game.weather == "濃霧" and c["id"] != "Drone": v //= 2
            if game.weather == "豪雨" and c["id"] == "Concrete": v -= 5
            s += v
        game.players[pid]["score"] = s

@socketio.on('end_turn')
def end_turn(data):
    if data['player_id'] != game.turn: return
    game.turn = "p2" if game.turn == "p1" else "p1"
    if game.turn == "p1":
        game.turn_count += 1
        game.weather = random.choice(["晴天", "晴天", "豪雨", "濃霧"])
    p = game.players[game.turn]
    p["max_ap"] = min(p["max_ap"] + 1, 15)
    upkeep = sum(c.get("upkeep", 0) for c in p["field"])
    p["ap"] = p["max_ap"] - upkeep + sum(1 for c in p["field"] if c["id"] == "Clerk")
    while p["ap"] < 0 and p["field"]:
        p["field"].pop(0)
        p["ap"] = p["max_ap"] - sum(c.get("upkeep", 0) for c in p["field"])
    if p["deck"]: p["hand"].append(p["deck"].pop(0))
    recalc_scores()
    emit('update_ui', vars(game), broadcast=True)

if __name__ == '__main__':
    socketio.run(app, debug=True)